package models;

import lombok.Data;

/**
 * Main entity of the collection.
 * 
 * Consists representation of human.
 * 
 */
@Data
public class Human {
    private long id; // Greater then zero. Unique. Autogenerated.
    private String name; // Not null. Not empty
    // private Coordinates coordinates; // Not null.
    private java.time.LocalDateTime creationDate; // Not null. Autogenerated.
    private boolean realHero;
    private boolean hasToothpick;
    private double impactSpeed;
    private String soundtrackName; // Not null.
    private Float minutesOfWaiting; // Can be null
    // private Mood mood; // Can be null
    // private Car car; // Not null.
}
